import cart from "../../pageObjects/cart"
import productPage from "../../pageObjects/productPage"
import login from "../../pageObjects/login"
import register from "../../pageObjects/register"

describe('Cart tests', () => {
    beforeEach(() => {
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.pageTitle.should('be.visible').and('contain.text', 'Cart')
    })

    it('Empty cart test', () => {
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.pageTitle.should('be.visible').and('contain.text', 'Cart')
        cart.emptyCartMessage.should('be.visible').and('contain.text', 'Your cart is currently empty.')
        cart.backwardCartButton.should('exist').and('contain.text', 'Return to shop')
    })

    it('Add product to cart and proceed to cart', () => {
        cy.addToCart()
        login.resetPasswordSuccessMessage.should('exist').and('contain.text', 'has been added to your cart')
        productPage.viewCartButton.should('exist')
        productPage.viewCartButton.click()
        cy.url().should('include', '/cart/')
        productPage.pageBreadCrumbs.should('exist').and('contain.text', 'Cart')
        cart.cartNameAndTotal.should('exist').and('contain.text', 'Cart(1)')
        cart.cartThead.should('exist')
    })

    it('Click product picture', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.productPictureThumbnail.should('exist')
        cart.productPictureThumbnail.click()
        cy.url().should('include', '/product/black-lux-graphic-t-shirt/')
        cart.pageTitle.should('be.visible').and('contain.text', 't-shirt')
        productPage.pageBreadCrumbs.should('exist').and('contain.text', 't-shirt')
        productPage.addToCartButton.should('exist').and('contain.text', 'Add to cart')
    })

    it('Click product name', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.productName.should('exist')
        cart.productName.click()
        cy.url().should('include', '/product/black-lux-graphic-t-shirt/')
        cart.pageTitle.should('be.visible').and('contain.text', 't-shirt')
        productPage.pageBreadCrumbs.should('exist').and('contain.text', 't-shirt')
        productPage.addToCartButton.should('exist').and('contain.text', 'Add to cart')
    })

    it('Change product quantity and update cart', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.quantityInputField.should('exist').and('contain.value', '1')
        cart.quantityInputField.clear()
        cart.quantityInputField.type('2')
        cart.updateCartButton.should('exist')
        cart.updateCartButton.click()
        login.resetPasswordSuccessMessage.should('exist').and('contain.text', 'Cart updated')
        cart.quantityInputField.should('exist').and('contain.value', '2')
        cart.quantityPlusButton.should('exist')
        cart.quantityPlusButton.click()
        cart.updateCartButton.should('exist')
        cart.updateCartButton.click()
        login.resetPasswordSuccessMessage.should('exist').and('contain.text', 'Cart updated')
        cart.quantityInputField.should('exist').and('contain.value', '3')
        cart.quantityMinusButton.should('exist')
        cart.quantityMinusButton.click()
        cart.updateCartButton.should('exist')
        cart.updateCartButton.click()
        login.resetPasswordSuccessMessage.should('exist').and('contain.text', 'Cart updated')
        cart.quantityInputField.should('exist').and('contain.value', '2')
    })

    it('Delete product from cart', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.quantityInputField.should('exist').and('contain.value', '1')
        cart.deleteProductFromCartButton.should('exist')
        cart.deleteProductFromCartButton.click()
        login.resetPasswordSuccessMessage.should('exist').and('contain.text', ' removed')
    })

    it('Clear cart', () => {
        cy.addToCart()
        productPage.secondProductPageLink()
        productPage.productColorSelect.should('exist')
        productPage.productColorSelect.select(1)
        productPage.productSizeSelect.should('exist')
        productPage.productSizeSelect.select(1)
        productPage.addToCartButton.should('exist').and('contain.text', 'Add to cart')
        productPage.addToCartButton.click()
        productPage.thirdProductPageLink()
        productPage.productColorSelect.should('exist')
        productPage.productColorSelect.select(1)
        productPage.productSizeSelect.should('exist')
        productPage.productSizeSelect.select(1)
        productPage.addToCartButton.should('exist').and('contain.text', 'Add to cart')
        productPage.addToCartButton.click()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.cartNameAndTotal.should('exist').and('contain.text', 'Cart(3)')
        cart.deleteProductFromCartButton.should('exist')
        cart.deleteProductFromCartButton.first().click()
        cart.emptyCartMessage.should('not.exist')
        cart.cartNameAndTotal.should('exist').and('contain.text', 'Cart(2)')
        cart.clearCart.should('exist').and('contain.text', 'clear shopping cart')
        cart.clearCart.click()
        cy.url().should('include', '/cart/?empty-cart')
        cart.emptyCartMessage.should('be.visible').and('contain.text', 'Your cart is currently empty.')
        cart.cartNameAndTotal.should('exist').and('contain.text', 'Cart(0)')
    })

    it('Undo product delete from cart', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.quantityInputField.should('exist').and('contain.value', '1')
        cart.deleteProductFromCartButton.should('exist')
        cart.deleteProductFromCartButton.click()
        login.resetPasswordSuccessMessage.should('exist').and('contain.text', ' removed')
        cart.undoDeleteProductFromCart.should('exist')
        cart.undoDeleteProductFromCart.click()
        cy.url().should('include', '/cart/')
        productPage.pageBreadCrumbs.should('exist').and('contain.text', 'Cart')
        cart.cartNameAndTotal.should('exist').and('contain.text', 'Cart(1)')
        cart.cartThead.should('exist')
        cart.productPictureThumbnail.should('exist')
        cart.productName.should('exist')
    })

    it('Discount code test', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.quantityInputField.should('exist').and('contain.value', '1')
        cart.discountCodeBlock.should('exist').and('contain.text', 'Enter your code if you have one')
        cart.discountCodeInputField.should('exist')
        cart.discountCodeInputField.type('testCode')
        cart.discountCodeApplyButton.should('exist').and('contain.text', 'Apply Coupon')
        cart.discountCodeApplyButton.click()
        register.errorMessage.should('exist').and('contain.text', 'does not exist!')
    })

    it('Continue Shopping', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.quantityInputField.should('exist').and('contain.value', '1')
        cart.continueShoppingButton.should('exist')
        cart.continueShoppingButton.click()
        cy.url().should('include', '/shop/')
        productPage.pageBreadCrumbs.should('exist').and('contain.text', 'Shop')
    })

    it('Proceed to checkout', () => {
        cy.addToCart()
        cart.cartPageLink()
        cy.url().should('include', '/cart/')
        cart.quantityInputField.should('exist').and('contain.value', '1')
        cart.proceedToCheckoutButton.should('exist')
        cart.proceedToCheckoutButton.click()
        cy.url().should('include', '/checkout/')
        productPage.pageBreadCrumbs.should('exist').and('contain.text', 'Checkout')
    })
})